=== sjctrags69/FETPTraining2026/GecoleaJEx14/src/main/resources/files/myday.dtd
<!ELEMENT date (day,month,year?)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>

<!ELEMENT a (date*)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT c (b+ | (b?, a)*)>

=== sjctrags69/FETPTraining2026/GecoleaJEx14/src/main/resources/files/myday3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE c SYSTEM "myday.dtd">

<c>
    <b>First</b>
    <a>
        <date>
            <day>1</day>
            <month>January</month>
        </date>
    </a>

    <a>
        <date>
            <day>14</day>
            <month>February</month>
            <year>2025</year>
        </date>
    </a>
</c>

=== sjctrags69/FETPTraining2026/GecoleaJEx14/src/main/resources/files/myday2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE c SYSTEM "myday.dtd">

<c>
    <b>Optional text</b>
    <a>
        <date>
            <day>25</day>
            <month>March</month>
            <year>2026</year>
        </date>
        <date>
            <day>26</day>
            <month>March</month>
        </date>
    </a>
</c>
