=== sjctrags69/FETPTraining2026/dolbajex14/src/main/resources/files/library.dtd
<!ELEMENT library (book | journal | misc)*>

<!ELEMENT book (title, editor?, publisher?)>
<!ATTLIST book id CDATA #REQUIRED>

<!ELEMENT journal (title, volume?, number?)>
<!ATTLIST journal
	id CDATA #REQUIRED
	publ_year CDATA #IMPLIED>

<!ELEMENT misc (author*, title, year?, pages?)>
<!ATTLIST misc id CDATA #REQUIRED>

<!ELEMENT title (#PCDATA)>
<!ELEMENT editor (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT volume (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT pages (#PCDATA)>

=== sjctrags69/FETPTraining2026/dolbajex14/src/main/resources/files/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library>
  <book id="2003-Blanken">
    <title>Intelligent XML Search</title>
    <editor>Henk A. Blanken et al.</editor>
    <publisher>Springer Verlag</publisher>
  </book>
  <journal id="TODS_1_2003" publ_year="2003">
    <title>ACM Transactions on Databases</title>
    <volume>24</volume>
    <number>1</number>
  </journal>
  <misc id="Dipl2002-12">
    <author>U. Known</author>
    <title>The Diploma Thesis that did not appear</title>
    <year>2002</year>
    <pages>0</pages>
  </misc>
</library>
